logger:
  logLevel: DEBUG
  logFileEnable: true
  logStdoutEnable: true
  logFile: ./out.log
  maxSize: 500
  maxAge: 28
  maxBackups: 7
  rewriteLog: true
server:
  readTimeout: 200ms
  writeTimeout: 200ms
  idleTimeout: 10s
database:
  port: 5432
  host: 192.168.0.32
  dbName: www
  user: sysadmin
  password: w3X{77PpCR
  driver: postgres
  connect: true # разрешение на коннект
  connectionTimeout: 10s
rtsp:
  run: #usr/bin/av_reader-1.1.7/av_reader --config_file /etc/rss/rss-av_reader.yml --port %s --stream_path %s --camera_id %s
  refreshTime: 10s # периодичность запроса и сверки
  url: http://10.100.100.228:9997 # адрес для подключения к api rtsp-simple-server
  api:  
    urlGet: /v1/paths/list
    urlAdd: /v1/config/paths/add/
    urlRemove: /v1/config/paths/remove/
    urlEdit: /v1/config/paths/edit/