// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Kseniya-cha/System-for-raising-video-streams/internal/statusstream (interfaces: Common)

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	reflect "reflect"

	statusstream "github.com/Kseniya-cha/System-for-raising-video-streams/internal/statusstream"
	customError "github.com/Kseniya-cha/System-for-raising-video-streams/pkg/customError"
	gomock "github.com/golang/mock/gomock"
)

// MockCommon is a mock of Common interface.
type MockCommon struct {
	ctrl     *gomock.Controller
	recorder *MockCommonMockRecorder
}

// MockCommonMockRecorder is the mock recorder for MockCommon.
type MockCommonMockRecorder struct {
	mock *MockCommon
}

// NewMockCommon creates a new mock instance.
func NewMockCommon(ctrl *gomock.Controller) *MockCommon {
	mock := &MockCommon{ctrl: ctrl}
	mock.recorder = &MockCommonMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommon) EXPECT() *MockCommonMockRecorder {
	return m.recorder
}

// Insert mocks base method.
func (m *MockCommon) Insert(arg0 context.Context, arg1 *statusstream.StatusStream) customError.IError {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Insert", arg0, arg1)
	ret0, _ := ret[0].(customError.IError)
	return ret0
}

// Insert indicates an expected call of Insert.
func (mr *MockCommonMockRecorder) Insert(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Insert", reflect.TypeOf((*MockCommon)(nil).Insert), arg0, arg1)
}
